#!/bin/bash

TMP_FILE=$(mktemp)

timeout 30 cif_parse "$@" >/dev/null 2> "$TMP_FILE"
STATUS=$?

if [ "$STATUS" = 124 ]
then
    echo --
elif [ "$STATUS" != 0 ]
then
    echo ERROR
elif grep -q ': warning\[' "$TMP_FILE"
then
    echo WARNING
fi

rm -f "$TMP_FILE"
